version: '3.4'

networks:
  myappnetwork:
    name: myappnetwork

services:
  thewebapplication:
    image: ${DOCKER_REGISTRY-}thewebapplication
    build:
      context: .
      dockerfile: TheWebApplication/Dockerfile
    links:
      - sqldata
    depends_on:
      - sqldata
      - theconsoleprogram
    networks:
      - myappnetwork

  theconsoleprogram:
    image: ${DOCKER_REGISTRY-}theconsoleprogram
    build:
      context: .
      dockerfile: TheConsoleProgram/Dockerfile
    links:
      - sqldata
    depends_on:
      - "sqldata"
    networks:
      - myappnetwork

  sqldata:  
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "MyPass@word"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:  
      - '1440:1433'
    networks:
      - myappnetwork
